server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:carbon_trade
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.example: DEBUG
    org.springframework: INFO 